namespace WinUI3Package
{
    [bindable]
    [default_interface]
    runtimeclass AncestorSource : Microsoft.UI.Xaml.DependencyObject
    {
        AncestorSource();
       
        static Microsoft.UI.Xaml.DependencyProperty AncestorTypeProperty{ get; };
        static void SetAncestorType(Microsoft.UI.Xaml.FrameworkElement element, String type);
        static String GetAncestorType(Microsoft.UI.Xaml.FrameworkElement element);

        static Microsoft.UI.Xaml.DependencyProperty AncestorProperty{ get; };
        static void SetAncestor(Microsoft.UI.Xaml.FrameworkElement element, Object value);
        static Object GetAncestor(Microsoft.UI.Xaml.FrameworkElement element);
    }
}
