namespace WinUI3Package
{
    static runtimeclass AutoSuggestBoxHelper
    {
        static Microsoft.UI.Xaml.DependencyProperty AcrylicWorkaroundProperty{get; };
        static Boolean GetAcrylicWorkaround(Microsoft.UI.Xaml.Controls.AutoSuggestBox autoSuggestBox);
        static void SetAcrylicWorkaround(Microsoft.UI.Xaml.Controls.AutoSuggestBox autoSuggestBox, Boolean value);
    }
}
