namespace WinUI3Package
{
    static runtimeclass ComboBoxHelper
    {
        static Microsoft.UI.Xaml.DependencyProperty AcrylicWorkaroundProperty{get; };
        static Boolean GetAcrylicWorkaround(Microsoft.UI.Xaml.Controls.ComboBox comboBox);
        static void SetAcrylicWorkaround(Microsoft.UI.Xaml.Controls.ComboBox comboBox, Boolean value);
    }
}
