
import "ContentDialogWindowButtonClickEventArgs.idl";
import "ContentDialogContent.idl";

namespace WinUI3Package
{
    [default_interface]
    unsealed runtimeclass ContentDialogWindow : Microsoft.UI.Xaml.Window
    {
        ContentDialogWindow();

        void Open();

        void Hide();

        void UpdateWindowSize();

        void SetParent(Microsoft.UI.Xaml.Window parent, Boolean center);

        Windows.Foundation.IAsyncOperation<Microsoft.UI.Xaml.Controls.ContentDialogResult> ShowAsync();

        Microsoft.UI.Xaml.Media.Imaging.BitmapImage HeaderImage{ get; set; };
        String HeaderImageUri{ get; set; };

        Microsoft.UI.Xaml.Controls.ContentDialogResult Result{ get; set; };

        Boolean HasTitleBar{ get; set; };
        Boolean IsResizable{ get; set; };

        event Windows.Foundation.TypedEventHandler<WinUI3Package.ContentDialogWindow, Object> Loaded;
        event Windows.Foundation.TypedEventHandler<WinUI3Package.ContentDialogWindow, Object> Opened;

        event Windows.Foundation.TypedEventHandler<Object, Microsoft.UI.Xaml.Input.RightTappedRoutedEventArgs> ContentRightTapped;

        event Windows.Foundation.TypedEventHandler<WinUI3Package.ContentDialogWindow, WinUI3Package.ContentDialogWindowButtonClickEventArgs> PrimaryButtonClick;
        event Windows.Foundation.TypedEventHandler<WinUI3Package.ContentDialogWindow, WinUI3Package.ContentDialogWindowButtonClickEventArgs> SecondaryButtonClick;
        event Windows.Foundation.TypedEventHandler<WinUI3Package.ContentDialogWindow, WinUI3Package.ContentDialogWindowButtonClickEventArgs> CloseButtonClick;

    }
}
