namespace WinUI3Package
{
    [bindable]
    [default_interface]
    runtimeclass Convert 
    {
		static Single DoubleToSingle(Double value);
        
        static Boolean ContainerToBool(Windows.Foundation.Collections.IVector<Object> container);
        static Boolean ReferenceToBool(Object value);
        static Boolean StringToBool(String value);
        static Boolean VisibilityToBool(Microsoft.UI.Xaml.Visibility value);

        static Boolean ContainerToBoolReverse(Windows.Foundation.Collections.IVector<Object> container);
        static Boolean ReferenceToBoolReverse(Object value);
        static Boolean StringToBoolReverse(String value);
        static Boolean VisibilityToBoolReverse(Microsoft.UI.Xaml.Visibility value);

        static Microsoft.UI.Xaml.Visibility ContainerToVisibility(Windows.Foundation.Collections.IVector<Object> container);
        static Microsoft.UI.Xaml.Visibility ReferenceToVisibility(Object value);
        static Microsoft.UI.Xaml.Visibility StringToVisibility(String value);
        static Microsoft.UI.Xaml.Visibility BoolToVisibility(Boolean value);
        
        static Microsoft.UI.Xaml.Visibility ContainerToVisibilityReverse(Windows.Foundation.Collections.IVector<Object> container);
        static Microsoft.UI.Xaml.Visibility ReferenceToVisibilityReverse(Object value);
        static Microsoft.UI.Xaml.Visibility StringToVisibilityReverse(String value);
        static Microsoft.UI.Xaml.Visibility BoolToVisibilityReverse(Boolean value);

        static Boolean ReverseBool(Boolean value);
        static Microsoft.UI.Xaml.Visibility ReverseVisibility(Microsoft.UI.Xaml.Visibility value);
    }
}
