import "CustomBackdropBase.idl";

namespace WinUI3Package
{
    [bindable]
    [default_interface]
    runtimeclass CustomAcrylicBackdrop : CustomBackdropBase
    {
        CustomAcrylicBackdrop();
        
        Microsoft.UI.Composition.SystemBackdrops.DesktopAcrylicKind Kind;
        static Microsoft.UI.Xaml.DependencyProperty KindProperty{ get; };

        Microsoft.UI.Xaml.ElementTheme RequestedTheme;
        static Microsoft.UI.Xaml.DependencyProperty RequestedThemeProperty{ get; };
    }
}
