import "CustomBackdropBase.idl";

namespace WinUI3Package
{
    [bindable]
    [default_interface]
    runtimeclass CustomMicaBackdrop : CustomBackdropBase
    {
        CustomMicaBackdrop();

        Microsoft.UI.Composition.SystemBackdrops.MicaKind Kind;
        static Microsoft.UI.Xaml.DependencyProperty KindProperty{ get; };
    }
}
