namespace WinUI3Package
{
    [bindable]
    [default_interface]
    unsealed runtimeclass CustomBackdropBase : Microsoft.UI.Xaml.Media.SystemBackdrop
    {
        CustomBackdropBase();

        Boolean EnableWhenInactive;
        static Microsoft.UI.Xaml.DependencyProperty EnableWhenInactiveProperty{ get; };

        Windows.UI.Color FallbackColor;
        static Microsoft.UI.Xaml.DependencyProperty FallbackColorProperty{ get; };

        Single LuminosityOpacity;
        static Microsoft.UI.Xaml.DependencyProperty LuminosityOpacityProperty{ get; };

        Windows.UI.Color TintColor;
        static Microsoft.UI.Xaml.DependencyProperty TintColorProperty{ get; };

        Single TintOpacity;
        static Microsoft.UI.Xaml.DependencyProperty TintOpacityProperty{ get; };
    }
}
