namespace WinUI3Package
{
    [bindable]
    [default_interface]
    runtimeclass DatePickerHelper 
    {
        static Microsoft.UI.Xaml.DependencyProperty AcrylicWorkaroundProperty{ get; };
        static Boolean GetAcrylicWorkaround(Microsoft.UI.Xaml.Controls.DatePicker datePicker);
        static void SetAcrylicWorkaround(Microsoft.UI.Xaml.Controls.DatePicker datePicker, Boolean value);
    }
}
