namespace WinUI3Package
{
    [bindable]
    [default_interface]
    runtimeclass GeneratedIconSource 
    {
        GeneratedIconSource();
        
        String Text;
        Windows.UI.Color Foreground;
        Windows.UI.Text.FontWeight FontWeight;
        Microsoft.UI.Xaml.Media.FontFamily FontFamily;
    }
}
