namespace WinUI3Package
{
    [Microsoft.UI.Xaml.Data.Bindable]
    [default_interface]
    unsealed runtimeclass GroupBox : Microsoft.UI.Xaml.Controls.ContentControl
    {
        GroupBox();

        //This really should be String, but it fucked up the compilation, because of https://github.com/microsoft/microsoft-ui-xaml/issues/8994
        //This type was original Object, and the above issue is fixed in winui3
        String Header;
    }
}
