namespace WinUI3Package
{
    [bindable]
    [default_interface]
    runtimeclass HostBackdrop : Microsoft.UI.Xaml.Media.SystemBackdrop
    {
        HostBackdrop();

        Single BlurAmount;
        static Microsoft.UI.Xaml.DependencyProperty BlurAmountProperty{ get; };
    }
}
