namespace WinUI3Package
{
    [bindable]
    [default_interface]
    runtimeclass IsNullOrEmptyStateTrigger : Microsoft.UI.Xaml.StateTriggerBase
    {
        IsNullOrEmptyStateTrigger();
        Object Value;
        static Microsoft.UI.Xaml.DependencyProperty ValueProperty{ get; };
    }
}
