namespace WinUI3Package
{
    runtimeclass MediaPlayerElementHelper 
    {
		static Microsoft.UI.Xaml.DependencyProperty AcrylicWorkaroundProperty{get; };
        static Boolean GetAcrylicWorkaround(Microsoft.UI.Xaml.Controls.MediaPlayerElement MediaPlayerElement);
		static void SetAcrylicWorkaround(Microsoft.UI.Xaml.Controls.MediaPlayerElement MediaPlayerElement, Boolean value);
    }
}
