namespace WinUI3Package
{
    [bindable]
    [default_interface]
    runtimeclass MicaBackdropWithFallback : Microsoft.UI.Xaml.Media.MicaBackdrop
    {
        MicaBackdropWithFallback();
        MicaBackdropWithFallback(Microsoft.UI.Xaml.Media.SystemBackdrop fallback);
        
        Microsoft.UI.Xaml.Media.SystemBackdrop Fallback;
    }
}
