namespace WinUI3Package
{
    [default_interface]
    runtimeclass ModernStandardWindowContextMenu : Microsoft.UI.Xaml.Controls.MenuFlyout
    {
        ModernStandardWindowContextMenu();

        Microsoft.UI.Xaml.Window Window;
    }
}
