namespace WinUI3Package
{
    [bindable]
    [default_interface]
    runtimeclass NonMaximizableWindowWorkaround 
    {
        NonMaximizableWindowWorkaround();
        NonMaximizableWindowWorkaround(Microsoft.UI.Xaml.Window window, Boolean isMaximizable);

        Microsoft.UI.Xaml.Window Window;
        Boolean IsMaximizable;
    }
}
