import "TransparentWindow.idl";

namespace WinUI3Package
{
    [Microsoft.UI.Xaml.Data.Bindable]
    [default_interface]
    [contentproperty("WindowContent")]
    runtimeclass RoundedAnimatedAcrylicWindowWithShadow : Microsoft.UI.Xaml.Window
    {
        RoundedAnimatedAcrylicWindowWithShadow();

        Microsoft.UI.Xaml.CornerRadius CornerRadius;
        Microsoft.UI.Xaml.Media.Animation.Storyboard EntranceStoryboard;
        Microsoft.UI.Xaml.Media.Animation.Storyboard ExitStoryboard;

        Microsoft.UI.Xaml.UIElement WindowContent;

        static Windows.Foundation.TimeSpan DurationToTimeSpan(Microsoft.UI.Xaml.Duration duration);
    }
}
