namespace WinUI3Package
{
    [bindable]
    [default_interface]
    runtimeclass SettingsExpanderLastItemConrnerRadiusConverter : Microsoft.UI.Xaml.Data.IValueConverter
    {
        SettingsExpanderLastItemConrnerRadiusConverter();
    }
}
