namespace WinUI3Package
{
    [bindable]
    [default_interface]
    runtimeclass Shimmer : Microsoft.UI.Xaml.Controls.ContentControl
    {
        Shimmer();
        
        Boolean IsLoading;
        static Microsoft.UI.Xaml.DependencyProperty IsLoadingProperty{ get; };
    }
}
