import "GeneratedIconSource.idl";

namespace WinUI3Package
{
    [bindable]
    [default_interface]
    [contentproperty("RightClickMenu")]
    runtimeclass TaskbarIcon /*: Microsoft.UI.Xaml.DependencyObject*/
    {
        TaskbarIcon();
        
        /*Tooltip*/
        Microsoft.UI.Xaml.UIElement ToolTip;


        /*Icons*/
        GeneratedIconSource IconSource;
        Windows.Foundation.Uri Icon;
        String IconFile;

        /*Theme-adapting icons*/
        GeneratedIconSource LightThemeIconSource;
        Windows.Foundation.Uri LightThemeIcon;
        String LightThemeIconFile;
        
        GeneratedIconSource DarkThemeIconSource;
        Windows.Foundation.Uri DarkThemeIcon;
        String DarkThemeIconFile;

        /*Right click*/
        Microsoft.UI.Xaml.Controls.MenuFlyout RightClickMenu;
        Microsoft.UI.Xaml.ElementTheme MenuTheme;

        void Show();
        void Remove();
    }
}
