namespace WinUI3Package
{
    [bindable]
    [default_interface]
	runtimeclass ThemeSettings : Microsoft.UI.Xaml.Data.INotifyPropertyChanged
	{
		static ThemeSettings Instance{ get; };

		Boolean AppsUseLightTheme{get; };
		Boolean ColorPrevalence{ get; };
		Boolean EnableTransparency{ get; };
		Boolean SystemUsesLightTheme{ get; };

		Windows.UI.Color AccentColor{ get; };
		Microsoft.UI.Xaml.Media.SolidColorBrush AccentColorBrush{ get; };
		Windows.UI.Color ColorizationColor{ get; };
		Microsoft.UI.Xaml.Media.SolidColorBrush ColorizationColorBrush{ get; };

		//Object is actually Windows.UI.Color
		Windows.Foundation.Collections.IVector<Object> ColorHistory{ get; };

		//Object is actually Microsoft.UI.Xaml.Media.SolidColorBrush
		Windows.Foundation.Collections.IVector<Object> ColorHistoryBrushes{ get; };
    }
}
