import "PopupMenuFlyoutItem.idl";
import "PopupMenuFlyoutItemBase.idl";

namespace WinUI3Package
{
    [bindable]
    [default_interface]
    runtimeclass TogglePopupMenuFlyoutItem : WinUI3Package.PopupMenuFlyoutItem, WinUI3Package.PopupMenuFlyoutItemBase
    {
        TogglePopupMenuFlyoutItem();
        
        Boolean IsChecked;
        static Microsoft.UI.Xaml.DependencyProperty IsCheckedProperty{ get; };
    }
}
