namespace WinUI3Package
{
    static runtimeclass ToolTipHelper
    {
		static Microsoft.UI.Xaml.DependencyProperty AcrylicWorkaroundProperty{get; };
	    static Boolean GetAcrylicWorkaround(Microsoft.UI.Xaml.Controls.ToolTip toolTip);
		static void SetAcrylicWorkaround(Microsoft.UI.Xaml.Controls.ToolTip toolTip, Boolean value);
    }
}
