namespace WinUI3Package
{
    [Microsoft.UI.Xaml.Data.Bindable]
    [default_interface]
    unsealed runtimeclass TransparentWindow : Microsoft.UI.Xaml.Window
    {
        TransparentWindow();
    }
}
