import "SmokeLayerKind.idl";

namespace WinUI3Package
{
    [bindable]
    [default_interface]
    runtimeclass UnderlaySmokeLayerOptions 
    {
        UnderlaySmokeLayerOptions();

        SmokeLayerKind SmokeLayerKind;
        Microsoft.UI.Xaml.UIElement CustomSmokeLayer;
        Microsoft.UI.Xaml.ScalarTransition OpacityTransition;
    }
}
