namespace WinUI3Package
{
    [default_interface]
    runtimeclass WindowedContentDialog
    {
        WindowedContentDialog();
	    WindowedContentDialog(Microsoft.UI.Xaml.Controls.ContentDialog contentDialog);

        Microsoft.UI.Xaml.Controls.ContentDialog Content{ get; };

        Windows.Foundation.IAsyncOperation<Microsoft.UI.Xaml.Controls.ContentDialogResult> ShowAsync();
        Windows.Foundation.IAsyncOperation<Microsoft.UI.Xaml.Controls.ContentDialogResult> ShowAsync(Microsoft.UI.Xaml.Window parentWindow);
    }
}
