import "ContentDialogContent.idl";
import "Underlay.idl";
import "UnderlaySystemBackdropOptions.idl";

namespace WinUI3Package
{
    [default_interface]
    unsealed runtimeclass WindowedContentDialog : Microsoft.UI.Xaml.Window
    {
        WindowedContentDialog();

        void Open();

        void Hide();

        void UpdateWindowSize();

        void SetParent(Microsoft.UI.Xaml.Window parent, Boolean center);

        Windows.Foundation.IAsyncOperation<Microsoft.UI.Xaml.Controls.ContentDialogResult> ShowAsync();
        Windows.Foundation.IAsyncOperation<Microsoft.UI.Xaml.Controls.ContentDialogResult> ShowAsync(Microsoft.UI.Xaml.Window parent);

        WinUI3Package.ContentDialogContent ContentDialogContent{ get; };

        Microsoft.UI.Xaml.Media.Imaging.BitmapImage HeaderImage;
        String HeaderImageUri;

        Microsoft.UI.Xaml.Controls.ContentDialogResult Result{ get; };

        Boolean HasTitleBar;
        Boolean IsResizable;

        WinUI3Package.UnderlayMode Underlay;
        WinUI3Package.UnderlaySystemBackdropOptions UnderlaySystemBackdrop;

        Boolean CenterInParent;

        event Windows.Foundation.TypedEventHandler<WinUI3Package.WindowedContentDialog, Object> Loaded;
        event Windows.Foundation.TypedEventHandler<WinUI3Package.WindowedContentDialog, Object> Opened;
    }
}
