namespace WinUI3Package
{
    [bindable]
    [default_interface]
    runtimeclass WinUIAsyncEventArgs 
    {
        WinUIAsyncEventArgs();

        Windows.Foundation.Deferral GetDeferral();
        Windows.Foundation.IAsyncAction wait_for_deferrals();
        Boolean Cancel;
    }
}
