namespace PackageRoot
{
    static runtimeclass ImageExtension
    {
        static WinUINamespace.UI.Xaml.DependencyProperty FallbackSourceProperty{ get; };
        static void SetFallbackSource(WinUINamespace.UI.Xaml.Controls.Image image, WinUINamespace.UI.Xaml.Media.ImageSource source);
        static WinUINamespace.UI.Xaml.Media.ImageSource GetFallbackSource(WinUINamespace.UI.Xaml.Controls.Image image);
    }
}
