import "RowRequestedEventArgs.idl";
import "UpdateRowDataEventArgs.idl";

namespace PackageRoot
{
	interface ITableData
	{
		Int32 RowCount{ get; };
		Int32 RowRequested(RowRequestedEventArgs args);
		void SetData(Int32 row, Int32 column, Object value);

		event Windows.Foundation.EventHandler<UpdateRowDataEventArgs> UpdateRowData;
	};
}