namespace PackageRoot
{
    [bindable]
    [default_interface]
    runtimeclass ReferenceToVisibilityConverter : WinUINamespace.UI.Xaml.Data.IValueConverter
    {
        ReferenceToVisibilityConverter();
        Boolean Reverse;
    }
}
