namespace PackageRoot
{
    [bindable]
    [default_interface]
    unsealed runtimeclass SegmentedMarginConverter : WinUINamespace.UI.Xaml.Data.IValueConverter
    {
        SegmentedMarginConverter();

        WinUINamespace.UI.Xaml.Thickness LeftItemMargin;
        WinUINamespace.UI.Xaml.Thickness MiddleItemMargin;
        WinUINamespace.UI.Xaml.Thickness RightItemMargin;
    }
}
