namespace PackageRoot
{
    [bindable]
    [default_interface]
    runtimeclass SettingsExpanderLastItemConrnerRadiusConverter : WinUINamespace.UI.Xaml.Data.IValueConverter
    {
        SettingsExpanderLastItemConrnerRadiusConverter();
    }
}
