namespace PackageRoot
{
    [bindable]
    [default_interface]
    [contentproperty("Content")]
    runtimeclass TableColumn : WinUINamespace.UI.Xaml.DependencyObject
    {
        TableColumn();
        
        Object Content;
        static WinUINamespace.UI.Xaml.DependencyProperty ContentProperty{ get; };

        WinUINamespace.UI.Xaml.DataTemplate ItemTemplate;
		static WinUINamespace.UI.Xaml.DependencyProperty ItemTemplateProperty{ get; };

		WinUINamespace.UI.Xaml.DataTemplate EditTemplate;
		static WinUINamespace.UI.Xaml.DependencyProperty EditTemplateProperty{ get; };

        Boolean SortEnabled;
        static WinUINamespace.UI.Xaml.DependencyProperty SortEnabledProperty{ get; };

        Boolean IsResizable;
		static WinUINamespace.UI.Xaml.DependencyProperty IsResizableProperty{ get; };

        //These should be set during initialization. We don't listen for changes during runtime
        WinUINamespace.UI.Xaml.HorizontalAlignment HorizontalAlignment;
        Double MinWidth;
        Double MaxWidth;

        WinUINamespace.UI.Xaml.Controls.Flyout Flyout;
    }
}
