namespace PackageRoot
{
    [bindable]
    [default_interface]
    runtimeclass TableColumn : WinUINamespace.UI.Xaml.DependencyObject
    {
        TableColumn();
        
        String StringContent;
        //FrameworkElement UIContent;
        static WinUINamespace.UI.Xaml.DependencyProperty StringContentProperty{ get; };

        WinUINamespace.UI.Xaml.DataTemplate ItemTemplate;
		static WinUINamespace.UI.Xaml.DependencyProperty ItemTemplateProperty{ get; };

		WinUINamespace.UI.Xaml.DataTemplate EditTemplate;
		static WinUINamespace.UI.Xaml.DependencyProperty EditTemplateProperty{ get; };

        Boolean SortEnabled;
        static WinUINamespace.UI.Xaml.DependencyProperty SortEnabledProperty{ get; };
    }
}
