namespace PackageRoot
{
    [bindable]
    [default_interface]
    runtimeclass TableAlternateRowColor  //This has to be a runtimeclass to be able to define in Xaml
    {
        TableAlternateRowColor();
        
	    Windows.UI.Color ForegroundColor;
		Windows.UI.Color BackgroundColor;
    }
}
