import "TableColumnCollection.idl";

namespace PackageRoot
{
    [default_interface]
    runtimeclass Table : WinUINamespace.UI.Xaml.Controls.SwapChainPanel, WinUINamespace.UI.Xaml.Data.INotifyPropertyChanged
    {
        Table();
        
        //TODO: test only
        Int32 DataCount;
        Int32 Fps{ get; };

        Windows.UI.Color HeaderForeground;
        static WinUINamespace.UI.Xaml.DependencyProperty HeaderForegroundProperty{ get; };

        Windows.UI.Color HeaderHoveredForeground;
        static WinUINamespace.UI.Xaml.DependencyProperty HeaderHoveredForegroundProperty{ get; };

        Single HeaderFontSize;
        static WinUINamespace.UI.Xaml.DependencyProperty HeaderFontSizeProperty{ get; };

        Windows.UI.Text.FontWeight HeaderFontWeight;
        static WinUINamespace.UI.Xaml.DependencyProperty HeaderFontWeightProperty{ get; };

        Single ContentFontSize;
        static WinUINamespace.UI.Xaml.DependencyProperty ContentFontSizeProperty{ get; };

        WinUINamespace.UI.Xaml.Media.FontFamily FontFamily;
        static WinUINamespace.UI.Xaml.DependencyProperty FontFamilyProperty{ get; };

        Windows.UI.Text.FontWeight ContentFontWeight;
        static WinUINamespace.UI.Xaml.DependencyProperty ContentFontWeightProperty{ get; };

        WinUINamespace.UI.Xaml.Thickness ContentPadding;
        static WinUINamespace.UI.Xaml.DependencyProperty ContentPaddingProperty{ get; };

        TableColumnCollection Columns{ get; };
    }
}
