import "TableAlternateRowColor.idl";

namespace PackageRoot
{
    [bindable]
    [default_interface]
	runtimeclass TableAlternateRowColorCollection : Windows.Foundation.Collections.IIterable<TableAlternateRowColor>, Windows.Foundation.Collections.IVector<TableAlternateRowColor>
    {
        TableAlternateRowColorCollection();
    }
}
