namespace PackageRoot
{
    [bindable]
    [default_interface]
    runtimeclass TableColumn : WinUINamespace.UI.Xaml.DependencyObject
    {
        TableColumn();
        
        String StringContent;
        //FrameworkElement UIContent;
        static WinUINamespace.UI.Xaml.DependencyProperty StringContentProperty{ get; };

        Boolean SortEnabled;
        static WinUINamespace.UI.Xaml.DependencyProperty SortEnabledProperty{ get; };
    }
}
