namespace PackageRoot
{
    [default_interface]
    runtimeclass Table : WinUINamespace.UI.Xaml.Controls.SwapChainPanel, WinUINamespace.UI.Xaml.Data.INotifyPropertyChanged
    {
        Table();
        
        //TODO: test only
        Int32 DataCount;
        Int32 Fps{ get; };
    }
}
