namespace PackageRoot
{
    [bindable]
    [default_interface]
	[contentproperty("Type")]
	runtimeclass TypeNameExtension : WindowsNamespace.UI.Xaml.Markup.MarkupExtension
    {
        TypeNameExtension();
	    TypeNameExtension(Windows.UI.Xaml.Interop.TypeName type);
        Windows.UI.Xaml.Interop.TypeName Type;
    }
}
