namespace PackageRoot
{
    [bindable]
    [default_interface]
    runtimeclass WrapPanel : WinUINamespace.UI.Xaml.Controls.Panel
    {
        WrapPanel();
        
        Double HorizontalSpacing;
        static WinUINamespace.UI.Xaml.DependencyProperty HorizontalSpacingProperty{ get; };

        Double VerticalSpacing;
        static WinUINamespace.UI.Xaml.DependencyProperty VerticalSpacingProperty{ get; };

        WinUINamespace.UI.Xaml.Controls.Orientation Orientation;
        static WinUINamespace.UI.Xaml.DependencyProperty OrientationProperty{ get; };
    }
}
