import "ContributorItem.idl";

namespace WinUI3Example
{
    [default_interface]
	runtimeclass AboutPage : Microsoft.UI.Xaml.Controls.Page, Microsoft.UI.Xaml.Data.INotifyPropertyChanged
    {
        AboutPage();

        static String WASDKReleaseVersion{ get; };
        static String WASDKRuntimeVersion{ get; };

        static String FormatVersion(
            UInt32 major,
            UInt32 minor,
            UInt32 patch,
            UInt32 majorMinor,
            String channel
        );

        Int32 Stars{ get; };
        Int32 Forks{ get; };
        Int32 Issues{ get; };
        String UpdatedAt{ get; };
        String CommitMessage{ get; };

		Windows.Foundation.Collections.IVector<Object> Contributors{ get; };

        Microsoft.UI.Xaml.Visibility IsLoadingContributors{ get; };
        Boolean IsLoadingRepoInfo{ get; };
    }
}
