// Copyright (c) Microsoft Corporation and Contributors.
// Licensed under the MIT License.

namespace WinUI3Example
{
    [default_interface]
    runtimeclass BadgePage : Microsoft.UI.Xaml.Controls.Page
    {
        BadgePage();
    }
}
