namespace WinUI3Example
{
    [default_interface]
    runtimeclass CodeWindow : Microsoft.UI.Xaml.Window
    {
        CodeWindow();
       
        String WindowTitle{ get; };
        Windows.Foundation.Collections.IVector<Object> CodeItems{ get; };
    }
}
