namespace WinUI3Example
{
    [default_interface]
    runtimeclass CustomAcrylicWindow : Microsoft.UI.Xaml.Window
    {
        CustomAcrylicWindow();


        static Single DoubleToSingle(Double value);
    }
}
