namespace WinUI3Example
{
    [default_interface]
    runtimeclass DefaultAcrylicWindow : Microsoft.UI.Xaml.Window
    {
        DefaultAcrylicWindow();
        static Microsoft.UI.Composition.SystemBackdrops.DesktopAcrylicKind ToAcrylicKind(Object selection);
    }
}
