namespace WinUI3Example
{
    [default_interface]
    runtimeclass DefaultWindowCaptionButtonWorkaround : Microsoft.UI.Xaml.Window
    {
        DefaultWindowCaptionButtonWorkaround();
        Int32 MyProperty;
    }
}
