import "Language.idl";

namespace WinUI3Example
{
    [default_interface]
    runtimeclass Editor : Microsoft.UI.Xaml.Controls.UserControl
    {
        Editor();
        String Code;
        Language CodeLanguage;
    }
}
