// Copyright (c) Microsoft Corporation and Contributors.
// Licensed under the MIT License.

namespace WinUI3Example
{
    [default_interface]
    runtimeclass GroupBoxPage : Microsoft.UI.Xaml.Controls.Page
    {
        GroupBoxPage();
    }
}
