namespace WinUI3Example
{
    [default_interface]
    runtimeclass IconButtonPage : Microsoft.UI.Xaml.Controls.Page
    {
        IconButtonPage();

        Microsoft.UI.Xaml.Controls.ToggleSwitch ExpandToggle{ get; };
    }
}
