// Copyright (c) Microsoft Corporation and Contributors.
// Licensed under the MIT License.
namespace WinUI3Example
{
    [default_interface]
    runtimeclass MainWindow : WinUI3Package.WindowEx
    {
        MainWindow();

        static Windows.Foundation.Uri GetXamlUrl(String name);
        static Guid IconGuid{ get; };
    }
}
