// Copyright (c) Microsoft Corporation and Contributors.
// Licensed under the MIT License.

namespace WinUI3Example
{
    [default_interface]
    runtimeclass MarqueeTextPage : Microsoft.UI.Xaml.Controls.Page
    {
        MarqueeTextPage();
        WinUI3Package.MarqueeText Test{ get; };
    }
}
