namespace WinUI3Example
{
    [default_interface]
    runtimeclass MicaBackdropWithFallbackWindow : Microsoft.UI.Xaml.Window
    {
        MicaBackdropWithFallbackWindow();
        Int32 MyProperty;
    }
}
