namespace WinUI3Example
{
    [default_interface]
    runtimeclass MicaBackdropWithTenMicaFallback : Microsoft.UI.Xaml.Window
    {
        MicaBackdropWithTenMicaFallback();
        Int32 MyProperty;
    }
}
