namespace WinUI3Example
{
    [default_interface]
    runtimeclass SvgPage : Microsoft.UI.Xaml.Controls.Page
    {
        SvgPage();
        Windows.Foundation.Collections.IVector<Object> Svgs{ get; };

        static Windows.Foundation.Uri GetPngFromSvgUrl(Object svgUrl);
        static Microsoft.UI.Xaml.Media.ImageSource GetSvgImageSourceFromString(String svgContent);
    }
}
