namespace WinUI3Example
{
    [default_interface]
    runtimeclass TaskbarIconSource : Microsoft.UI.Xaml.Controls.UserControl, Microsoft.UI.Xaml.Data.INotifyPropertyChanged
    {
        TaskbarIconSource();

        Boolean IsFileSet{ get; };
    }
}
