namespace WinUI3Example
{
    [bindable]
    [default_interface]
    runtimeclass TemplateInformation
    {
        TemplateInformation();

        String Header1;
        String Regex1;
        String PlaceholderText1;
    }
}
