namespace WinUI3Example
{
    [default_interface]
    runtimeclass ThemeListenerPage : Microsoft.UI.Xaml.Controls.Page
    {
        ThemeListenerPage();
        
	    static String ElementThemeToString(Microsoft.UI.Xaml.ElementTheme theme);
    }
}
