namespace WinUI3Example
{
    [default_interface]
    runtimeclass WindowedContentDialogPage : Microsoft.UI.Xaml.Controls.Page
    {
        WindowedContentDialogPage();

        static String GetWindowedContentDialogSampleCppSource(WinUI3Package.UnderlayMode mode);
    }
}
