namespace UWPExample
{
    [default_interface]
    runtimeclass ExtensionsPage : Windows.UI.Xaml.Controls.Page
    {
        ExtensionsPage();
        Windows.UI.Xaml.Controls.ToggleSwitch ClipSwitch{ get; };
    }
}
