namespace UWPExample
{
    [default_interface]
    runtimeclass GroupBoxPage : Windows.UI.Xaml.Controls.Page
    {
        GroupBoxPage();

        Windows.UI.Xaml.Controls.RadioButton SingleClickRadio{ get; };
    }
}
