namespace UWPExample
{
    [default_interface]
    runtimeclass MainPage : Windows.UI.Xaml.Controls.Page
    {
        MainPage();

        Microsoft.UI.Xaml.Controls.NavigationViewItem HelpersItem{ get; };
		Microsoft.UI.Xaml.Controls.NavigationViewItem ControlsItem{ get; };
		Microsoft.UI.Xaml.Controls.NavigationViewItem ExtensionsItem{ get; };

        static String WindowTitle{ get; };
    }
}
