namespace UWPExample
{
    [default_interface]
    runtimeclass MarqueeContainerPage : Windows.UI.Xaml.Controls.Page
    {
        MarqueeContainerPage();

        Windows.UI.Xaml.Controls.Slider MarqueeSpeedSlider{ get; };
        Windows.UI.Xaml.Controls.Slider FontSizeSlider{ get; };
        Windows.UI.Xaml.Controls.Slider SpaceIntervalSlider{ get; };
        Windows.UI.Xaml.Controls.ToggleSwitch PauseOnHoverToggle{ get; };
        Windows.UI.Xaml.Controls.ComboBox MarqueeDirectionComboBox{ get; };
        Windows.UI.Xaml.Controls.ComboBox MarqueeBehaviorComboBox{ get; };

        static UWPPackage.MarqueeBehavior GetBehaviorFromIndex(Int32 value);
        static UWPPackage.MarqueeDirection GetDirectionFromIndex(Int32 value);

        //UWPExample.MarqueeContainer Test{ get; };
        UWPPackage.MarqueeText Test{ get; };
    }
}
