#pragma once
// The purpose of this file is to convert includes from the files generated by XamlCompiler into imports.
// For the .g.cpp files generated by the XamlCompiler, this file is added to the beginning of the include list via the `/FI`. For `.xaml.cpp` or `.xaml.h` files, it should be included before `xaml.h` or `xaml.g.h` but after other header files.

// Include SDK headers normally before importing C++/WinRT modules.
#include <windows.h>
#include <unknwn.h>
#undef GetCurrentTime

#define WINUIESSENTIALS_USE_STD_MODULE
import std;

// XAML-generated sources still include these STL headers after pch.h.
// With import std, skip reopening the same MSVC STL headers.
#ifndef _FUNCTIONAL_
#define _FUNCTIONAL_
#endif
#ifndef _MAP_
#define _MAP_
#endif
#ifndef _MEMORY_
#define _MEMORY_
#endif
#ifndef _REGEX_
#define _REGEX_
#endif
#ifndef _STRING_
#define _STRING_
#endif
#ifndef _VECTOR_
#define _VECTOR_
#endif

// The .cpp files generated by the XamlCompiler currently do not support modules. After defining this macro, all C++/WinRT header files will become empty.
#ifndef WINRT_ENABLE_LEGACY_COM
#define WINRT_ENABLE_LEGACY_COM
#endif
#ifndef WINRT_IMPORT_MODULE
#define WINRT_IMPORT_MODULE
#endif

// Import these modules to satisfy the requirements of the .cpp files generated by the XamlCompiler
// and the sample sources whose C++/WinRT projection headers are empty when WINRT_IMPORT_MODULE is set.
import winrt.UWPExample;
import winrt.UWPPackage;

import winrt.Microsoft.UI.Xaml.Controls;
import winrt.Microsoft.UI.Xaml.Controls.Primitives;
import winrt.Microsoft.UI.Xaml.XamlTypeInfo;
import winrt.Microsoft.Web.WebView2.Core;

import winrt.Windows.ApplicationModel;
import winrt.Windows.ApplicationModel.Activation;
import winrt.Windows.ApplicationModel.Core;
import winrt.Windows.Data.Json;
import winrt.Windows.Data.Xml.Dom;
import winrt.Windows.Foundation;
import winrt.Windows.Foundation.Collections;
import winrt.Windows.Foundation.Metadata;
import winrt.Windows.Globalization.DateTimeFormatting;
import winrt.Windows.Storage.Pickers;
import winrt.Windows.System;
import winrt.Windows.UI.Composition;
import winrt.Windows.UI.Core;
import winrt.Windows.UI.Notifications;
import winrt.Windows.UI.Popups;
import winrt.Windows.UI.StartScreen;
import winrt.Windows.UI.Xaml;
import winrt.Windows.UI.Xaml.Controls;
import winrt.Windows.UI.Xaml.Controls.Primitives;
import winrt.Windows.UI.Xaml.Data;
import winrt.Windows.UI.Xaml.Documents;
import winrt.Windows.UI.Xaml.Hosting;
import winrt.Windows.UI.Xaml.Input;
import winrt.Windows.UI.Xaml.Markup;
import winrt.Windows.UI.Xaml.Media;
import winrt.Windows.UI.Xaml.Media.Animation;
import winrt.Windows.UI.Xaml.Media.Imaging;
import winrt.Windows.UI.Xaml.Navigation;
import winrt.Windows.UI.Xaml.Shapes;
import winrt.Windows.UI.Xaml.Interop;
import winrt.Windows.Web.Http;
import winrt.Windows.Web.Http.Headers;

#include "NamedUrl.h"
#include "CodeSource.h"
#include "ControlExampleSubstitution.h"