namespace UWPExample
{
    [bindable]
    [default_interface]
    runtimeclass PhotoDataItemWithDimension 
    {
        PhotoDataItemWithDimension();

        Double Width;
        Double Height;

        String Title;
        String Category;
        String Thumbnail;
    }
}
