namespace UWPExample
{
    [default_interface]
    runtimeclass SegmentedPage : Windows.UI.Xaml.Controls.Page
    {
        SegmentedPage();

        /*BasicSegmentedExample*/
        Windows.UI.Xaml.Controls.ToggleSwitch EnabledSwitch1{ get; };
        Windows.UI.Xaml.Controls.ComboBox SelectionModeComboBox1{ get; };
        Windows.UI.Xaml.Controls.ComboBox HorizontalAlignmenmtComboBox1{ get; };

        Windows.UI.Xaml.Controls.ToggleSwitch EnabledSwitch2{ get; };
        Windows.UI.Xaml.Controls.ComboBox SelectionModeComboBox2{ get; };
        Windows.UI.Xaml.Controls.ComboBox HorizontalAlignmenmtComboBox2{ get; };

        Windows.UI.Xaml.Controls.ComboBox HorizontalAlignmenmtComboBox3{ get; };
        Windows.UI.Xaml.Controls.ToggleSwitch EnabledSwitch3{ get; };
        Windows.UI.Xaml.Controls.ComboBox SelectionModeComboBox3{ get; };

        Windows.UI.Xaml.Controls.ComboBox HorizontalAlignmenmtComboBox4{ get; };
        Windows.UI.Xaml.Controls.ToggleSwitch EnabledSwitch4{ get; };
        Windows.UI.Xaml.Controls.ComboBox SelectionModeComboBox4{ get; };
    }
}
