namespace UWPExample
{
    [default_interface]
    runtimeclass ShimmerPage : Windows.UI.Xaml.Controls.Page
    {
        ShimmerPage();

        Windows.UI.Xaml.Controls.ToggleSwitch IsLoadingSwitch{ get; };
    }
}
