namespace UWPExample
{
    [default_interface]
    runtimeclass SwitchPresenterPage : Windows.UI.Xaml.Controls.Page
    {
        SwitchPresenterPage();
        Windows.UI.Xaml.Controls.ToggleSwitch LoadingState{ get; };
    }
}
