namespace UWPExample
{
    [default_interface]
    runtimeclass UIElementExtensionsPage : Windows.UI.Xaml.Controls.Page
    {
        UIElementExtensionsPage();

        Windows.UI.Xaml.Controls.ToggleSwitch ClipSwitch{ get; };
    }
}
