namespace UWPPackage
{
    [bindable]
    [default_interface]
    runtimeclass EqualPanel : Windows.UI.Xaml.Controls.Panel
    {
        EqualPanel();

        Double HorizontalSpacing;
        static Windows.UI.Xaml.DependencyProperty HorizontalSpacingProperty{ get; };

        Double VerticalSpacing;
        static Windows.UI.Xaml.DependencyProperty VerticalSpacingProperty{ get; };

        Windows.UI.Xaml.Controls.Orientation Orientation;
        static Windows.UI.Xaml.DependencyProperty OrientationProperty{ get; };
    }
}
