#pragma once
#include <unknwn.h>
#include <winrt/Windows.Foundation.h>
#include <winrt/Windows.Foundation.Collections.h>
#include <winrt/Windows.UI.Xaml.h>
#include <winrt/Windows.UI.Core.h>
#include <winrt/Windows.UI.Xaml.Interop.h>
#include <winrt/Windows.UI.Xaml.Input.h>
#include "include/WinUIIncludes.hpp"
#include <winrt/Windows.UI.Xaml.Controls.h>
#include <winrt/Windows.UI.Xaml.Controls.Primitives.h>
#include <winrt/Windows.UI.Xaml.Media.Animation.h>

#include "GroupBox.h"
#include "IconButton.h"
#include "SettingsCard.h"
#include "SettingsExpander.h"
#include "Segmented.h"
#include "ProgressBarEx.h"
#include "MarqueeText.h"