#pragma once
#include <unknwn.h>
#include <winrt/Windows.Foundation.h>
#include <winrt/Windows.Foundation.Collections.h>
#include <winrt/Windows.UI.Xaml.h>
#include <winrt/Windows.UI.Core.h>
#include <winrt/Windows.UI.Xaml.Interop.h>
#include <winrt/Windows.UI.Xaml.Markup.h>
#include <winrt/Windows.UI.Xaml.Input.h>
#include "include/WinUIIncludes.hpp"
#include <winrt/Windows.UI.Xaml.Controls.h>
#include <winrt/Windows.UI.Xaml.Controls.Primitives.h>
#include <winrt/Windows.UI.Xaml.Media.Animation.h>
#include <winrt/Windows.UI.Xaml.Hosting.h>
#include <winrt/Windows.UI.Composition.h>
#include <winrt/Windows.UI.Xaml.Media.h>

#include "Case.h"
#include "CaseCollection.h"
#include "SwitchPresenter.h"
#include "TypeNameExtension.h"
#include "BoolToVisibilityConverter.h"
#include "ContainerToBoolConverter.h"
#include "ConverterGroup.h"
#include "NegateBoolConverter.h"
#include "StringToBoolConverter.h"
#include "ReferenceToBoolConverter.h"
#include "FontIconExtension.h"
#include "ControlSizeTrigger.h"
#include "IsEqualStateTrigger.h"
#include "IsNullOrEmptyStateTrigger.h"
#include "WrapPanel.h"
#include "DependentValue.h"
#include "SettingsCard.h"
#include "Shimmer.h"
#include "GroupBox.h"
#include "Segmented.h"