namespace UWPPackage
{
    [bindable]
    [default_interface]
    runtimeclass ProgressBarEx : Windows.UI.Xaml.Controls.ContentControl
    {
        ProgressBarEx();

        //HighColor for the highlight color
        Windows.UI.Color HighColor;
        static Windows.UI.Xaml.DependencyProperty HighColorProperty{ get; };

        //Base for the rest of the progress background color
        Windows.UI.Color BaseColor;
        static Windows.UI.Xaml.DependencyProperty BaseColorProperty{ get; };

        //0~100
        Double Percent;
        static Windows.UI.Xaml.DependencyProperty PercentProperty{ get; };

        //0~1.0
        Double Value;
        static Windows.UI.Xaml.DependencyProperty ValueProperty{ get; };

        /*
            Nope, I don't want to support listening for GradientStop changes in XAML, wasting too much performance
            because I have to listen for the VectorChange event and all the GradientStop property change event.
            The most important thing is, it's hard for users to get the effect looked right
        */
        //Windows.Foundation.Collections.IObservableVector<Windows.UI.Xaml.Media.GradientStop> GradientStops;
        //static Windows.UI.Xaml.DependencyProperty GradientStopsProperty{ get; };
    }
}
