namespace UWPPackage
{
    [bindable]
    [default_interface]
    runtimeclass SettingsExpanderLastItemConrnerRadiusConverter : Windows.UI.Xaml.Data.IValueConverter
    {
        SettingsExpanderLastItemConrnerRadiusConverter();
    }
}
