namespace UWPPackage
{
    [bindable]
    [default_interface]
    runtimeclass Shimmer : Windows.UI.Xaml.Controls.ContentControl
    {
        Shimmer();
        
        Boolean IsLoading;
        static Windows.UI.Xaml.DependencyProperty IsLoadingProperty{ get; };
    }
}
