namespace UWPPackage
{
    [bindable]
    [default_interface]
    runtimeclass WindowCaptionButtonThemeWorkaround : Windows.UI.Xaml.Controls.Control
    {
        WindowCaptionButtonThemeWorkaround();
    }
}
