namespace PackageRoot
{
    [bindable]
    [default_interface]
    runtimeclass ControlExampleSubstitution : WinUINamespace.UI.Xaml.DependencyObject
    {
        ControlExampleSubstitution();
        
        String Key;
        String Value;
        Boolean IsEnabled;
    }
}
