namespace PackageRoot
{
    [default_interface]
    runtimeclass ThemeToggleButton : WinUINamespace.UI.Xaml.Controls.Button
    {
        ThemeToggleButton();
        WinUINamespace.UI.Xaml.FrameworkElement Root;
    }
}
